const Logistics = () => {
  return (
    <div>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
      <p>Logistics</p>
    </div>
  )
}

export default Logistics
